apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-mlapi-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Release.Name }}-mlapi
    # Uncomment the line below if you really need to specify minimum replicas. It's not required anyway.
  # minReplicas: {{ .Values.replicaCount | default 1 }}
  maxReplicas: {{ .Values.hpaMaxReplicaCount | default 5 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpaCPUUtilizationCap | default 80 }}
