apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | default "sample"}}-mlapi-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP"}}
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-mlapi
