apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name }}-mlapi
  name: {{ .Release.Name }}-mlapi
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mlapi
  serviceName: {{ .Release.Name }}-mlapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mlapi
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: 
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        # Uncomment the line below especially of you are using an IPv6 environment. You can chage between "0.0.0.0" and "::" for the host IP.
        # Enabling critical logs only results in less logs printed to the console, and lets only custom errors be printed
        # command: ["uvicorn", "main:app", "--host", "::", "--port", "8000", "--log-level", "critical"]
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        name: api-server
        resources:
            requests:
                cpu: {{ .Values.resources.cpuRequests | default "10m" }}
                memory: {{ .Values.resources.memoryRequests | default "50Mi" }}
            limits:
                cpu: {{ .Values.resources.cpuLimits | default "50m" }}
                memory: {{ .Values.resources.memoryLimits | default "120Mi" }}
        ports:
        - containerPort: 8000
