apiVersion: v2
name: mlapi
description: Deploy a simple ML API application
type: application
maintainers:
  - name: zawadi-omari
    email: lernmat.mario@gmail.com

# Version number for the ML API application and should be incremented each time changes are
# made to the application. Might not follow semantic versioning
appVersion: "v0.0.1"

# This is the chart version that should be incremented each time changes are made in the
# repository, including templates, and app version
version: 1.0.0
