# Image values
image:
  repository: zawadimario/sample-api # Should be the same as the name of the image before colons
  # Do not manually change this tag because GitHub workflows will take care of it.
  tag: v1.0.2
  pullPolicy: ""

# Overrides for replicas. Use a number if you need to be specific
# e.g, replicaCount: 2
replicaCount: ""

# Overrides for countainer resources
# Change the values for resources as per API requirements
resources:
  cpuRequests: 10m
  memoryRequests: 50Mi
  cpuLimits: 50m
  memoryLimits: 130Mi

# Define k8s service
service:
  type: NodePort
  port: 8000

# Define HPA if you want to be specific. Currently 5 is the default maxReplicas. To modify the
# value, assign a suitable number or replicas e.g., hpaMaxReplicaCount: 7
hpaMaxReplicaCount: ""
# Specify a suitable % value for CPU Utilization cap e.g., hpaCPUUtilizationCap: 80
# Default is set to 80
hpaCPUUtilizationCap: ""
