# This workflow is responsible for linting the helm charts before building and pushing them
name: Lint and Test Charts

on: 
  workflow_dispatch:
  push:
    branches: main
    tags: "v*.*.*"
  pull_request:
    branches: main

jobs:
  lint-test:
    strategy:
      fail-fast: false
      # Used for spinning up a kind K8s cluster for helm install
      matrix:
        kubernetesVersion: [ "v1.24.15", "v1.28.0" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        
    # Linting requires python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create K8s kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.10.0
        with:
          node_image: "kindest/node:${{ matrix.kubernetesVersion }}"
          config: kind-config.yaml

      - name: Verify kind
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl get pods -n kube-system

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
